name: Release

on:
  push:
    branches:
    - master

jobs:
  release:
    runs-on: ubuntu-18.04

    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: latest
        prerelease: true
        title: Latest Build
